"""Deterministic synthetic telemetry.

Purpose and honest scope
------------------------
Waiting hours for a laptop to produce a rare event is not a development loop, so
these scenarios manufacture specific situations on demand: a build starting, a
charger being unplugged, a permanent behaviour change. They exist to make
behaviour *testable* -- "does the drift detector fire when the regime changes?"
is a question with a right answer only when we control the regime change.

They are **not** evidence about accuracy. Synthetic data is generated by a
process with known structure, so any model that recovers that structure will
look good. Every accuracy claim in this project is measured on recorded real
telemetry; synthetic runs are used for correctness, determinism and edge cases.
The results documentation states which is which.

Generation model
----------------
Signals are not independent noise. The couplings below are the ones that exist
on a real laptop, and they are what makes the data non-trivially predictable:

* **Workload leads CPU.** ``proc.cpu_build_pct`` moves first; aggregate CPU
  follows within a sample or two.
* **CPU leads temperature.** Silicon has thermal mass, modelled as a first-order
  lag with a ~90 s time constant, so temperature is a smoothed, delayed CPU.
* **Load drives power, power drains the battery.** Battery percent is the
  integral of power draw over capacity, not an independent random walk -- which
  is why a linear-trend baseline is genuinely strong on it.
* **Noise is autocorrelated** (AR(1)), because independent per-tick noise would
  make short-horizon persistence unbeatable and long-horizon forecasting
  impossible, neither of which is true of real telemetry.
"""

from __future__ import annotations

import math
import random
from dataclasses import dataclass, field

from ..telemetry.schema import (
    Quality,
    Reading,
    SignalKind,
    SignalRegistry,
    SignalSpec,
    TelemetrySample,
)

#: Signal space the scenarios emit. A subset of the live collector's 38, chosen
#: to cover every forecast target plus the drivers the couplings need.
SYNTHETIC_SPECS: tuple[SignalSpec, ...] = (
    SignalSpec("cpu.util_pct", "percent", SignalKind.GAUGE, 0.0, 100.0),
    SignalSpec("cpu.util_max_core_pct", "percent", SignalKind.GAUGE, 0.0, 100.0),
    SignalSpec("cpu.iowait_pct", "percent", SignalKind.GAUGE, 0.0, 100.0),
    SignalSpec("cpu.load1_per_core", "ratio", SignalKind.GAUGE, 0.0, 64.0),
    SignalSpec("cpu.freq_mhz", "megahertz", SignalKind.GAUGE, 0.0, 12000.0),
    SignalSpec("mem.used_pct", "percent", SignalKind.GAUGE, 0.0, 100.0),
    SignalSpec("mem.available_gb", "gigabyte", SignalKind.GAUGE, 0.0, 4096.0),
    SignalSpec("battery.percent", "percent", SignalKind.GAUGE, 0.0, 100.0,
               max_rate_per_s=0.5, max_hold_s=120.0),
    SignalSpec("battery.plugged", "bool", SignalKind.FLAG, 0.0, 1.0, max_hold_s=120.0),
    SignalSpec("battery.charging", "bool", SignalKind.FLAG, 0.0, 1.0, max_hold_s=120.0),
    SignalSpec("battery.power_w", "watt", SignalKind.GAUGE, 0.0, 400.0, max_hold_s=120.0),
    SignalSpec("gpu.util_pct", "percent", SignalKind.GAUGE, 0.0, 100.0),
    SignalSpec("gpu.power_w", "watt", SignalKind.GAUGE, 0.0, 800.0),
    SignalSpec("thermal.cpu_c", "celsius", SignalKind.GAUGE, -20.0, 130.0, max_rate_per_s=15.0),
    SignalSpec("disk.busy_pct", "percent", SignalKind.RATE, 0.0, 100.0),
    SignalSpec("net.recv_mbps", "megabyte_per_second", SignalKind.RATE, 0.0, 20000.0),
    SignalSpec("proc.concentration", "ratio", SignalKind.GAUGE, 0.0, 1.0),
    SignalSpec("proc.cpu_build_pct", "percent", SignalKind.GAUGE, 0.0, 6400.0),
    SignalSpec("proc.top1_cpu_pct", "percent", SignalKind.GAUGE, 0.0, 6400.0),
)


def synthetic_registry() -> SignalRegistry:
    return SignalRegistry(SYNTHETIC_SPECS)


@dataclass(slots=True)
class Segment:
    """A stretch of time with a target behaviour."""

    name: str
    duration_s: float
    #: Target level per driver signal. Missing keys hold their previous target.
    levels: dict[str, float] = field(default_factory=dict)
    #: AR(1) noise standard deviation per driver signal.
    noise: dict[str, float] = field(default_factory=dict)
    #: Seconds over which the level transitions from the previous segment's.
    ramp_s: float = 30.0
    plugged: bool | None = None
    #: Fraction of ticks where all signals are dropped, simulating a gap.
    dropout: float = 0.0


@dataclass(slots=True)
class ScenarioSpec:
    name: str
    segments: list[Segment]
    seed: int = 7
    interval_s: float = 5.0
    start_ts: float = 1_760_000_000.0
    battery_capacity_wh: float = 60.0
    battery_start_pct: float = 92.0
    description: str = ""

    @property
    def duration_s(self) -> float:
        return sum(s.duration_s for s in self.segments)


#: Driver signals the scenario specifies directly; everything else is derived.
_DRIVERS = ("cpu.util_pct", "gpu.util_pct", "mem.used_pct", "disk.busy_pct",
            "net.recv_mbps", "proc.cpu_build_pct")

_DEFAULT_LEVELS = {
    "cpu.util_pct": 5.0, "gpu.util_pct": 2.0, "mem.used_pct": 45.0,
    "disk.busy_pct": 1.0, "net.recv_mbps": 0.05, "proc.cpu_build_pct": 0.0,
}
_DEFAULT_NOISE = {
    "cpu.util_pct": 2.0, "gpu.util_pct": 1.0, "mem.used_pct": 0.3,
    "disk.busy_pct": 1.0, "net.recv_mbps": 0.05, "proc.cpu_build_pct": 1.0,
}

#: AR(1) coefficient for driver noise. 0.75 at a 5 s cadence gives a noise
#: autocorrelation time of ~17 s, matching what the real collector shows.
_AR = 0.75
#: Thermal time constant (seconds). Silicon plus heatsink, not instantaneous.
_THERMAL_TAU = 90.0
_IDLE_TEMP_C = 45.0
_TEMP_PER_CPU_PCT = 0.42
_IDLE_POWER_W = 6.0
_CPU_POWER_W = 0.38
_GPU_POWER_W = 0.55


def generate(spec: ScenarioSpec) -> tuple[list[TelemetrySample], SignalRegistry]:
    """Render a scenario into samples. Identical output for identical spec."""
    rng = random.Random(spec.seed)
    n_ticks = int(spec.duration_s / spec.interval_s)
    samples: list[TelemetrySample] = []

    target = dict(_DEFAULT_LEVELS)
    prev_target = dict(_DEFAULT_LEVELS)
    noise_state = dict.fromkeys(_DRIVERS, 0.0)
    temp_c = _IDLE_TEMP_C
    batt_pct = spec.battery_start_pct
    plugged = True
    seg_i = 0
    seg_elapsed = 0.0
    seg = spec.segments[0]
    prev_target = {k: _DEFAULT_LEVELS[k] for k in _DRIVERS}
    target = {**prev_target, **{k: v for k, v in seg.levels.items() if k in _DRIVERS}}
    if seg.plugged is not None:
        plugged = seg.plugged

    for i in range(n_ticks):
        ts = spec.start_ts + i * spec.interval_s
        if seg_elapsed >= seg.duration_s and seg_i + 1 < len(spec.segments):
            prev_target = _current_levels(prev_target, target, seg_elapsed, seg.ramp_s)
            seg_i += 1
            seg = spec.segments[seg_i]
            seg_elapsed = 0.0
            target = {**prev_target, **{k: v for k, v in seg.levels.items() if k in _DRIVERS}}
            if seg.plugged is not None:
                plugged = seg.plugged

        level = _current_levels(prev_target, target, seg_elapsed, seg.ramp_s)
        vals: dict[str, float] = {}
        for k in _DRIVERS:
            sd = seg.noise.get(k, _DEFAULT_NOISE[k])
            # AR(1) noise: e_t = ar * e_{t-1} + sqrt(1 - ar^2) * N(0, sd)
            noise_state[k] = _AR * noise_state[k] + math.sqrt(1 - _AR**2) * rng.gauss(0.0, sd)
            vals[k] = level[k] + noise_state[k]

        cpu = _clamp(vals["cpu.util_pct"], 0.0, 100.0)
        gpu = _clamp(vals["gpu.util_pct"], 0.0, 100.0)
        build = max(0.0, vals["proc.cpu_build_pct"])
        mem = _clamp(vals["mem.used_pct"], 0.0, 100.0)
        disk = max(0.0, vals["disk.busy_pct"])
        net = max(0.0, vals["net.recv_mbps"])

        # First-order thermal lag driven by CPU load.
        temp_target = _IDLE_TEMP_C + _TEMP_PER_CPU_PCT * cpu + 0.12 * gpu
        alpha = 1.0 - math.exp(-spec.interval_s / _THERMAL_TAU)
        temp_c += alpha * (temp_target - temp_c) + rng.gauss(0.0, 0.15)

        power_w = _IDLE_POWER_W + _CPU_POWER_W * cpu + _GPU_POWER_W * gpu
        charging = False
        if plugged:
            if batt_pct < 99.5:
                charging = True
                # Charge rate tapers near full, as real chargers do.
                charge_w = 45.0 * (1.0 - batt_pct / 100.0) ** 0.5
                batt_pct = min(100.0, batt_pct + _pct_delta(charge_w, spec, +1))
        else:
            batt_pct = max(0.0, batt_pct - _pct_delta(power_w, spec, +1))

        readings: dict[str, Reading] = {}
        if seg.dropout > 0.0 and rng.random() < seg.dropout:
            # Whole-sample dropout: the collector missed a tick.
            for spec_ in SYNTHETIC_SPECS:
                readings[spec_.name] = Reading(None, Quality.MISSING)
            samples.append(TelemetrySample(ts=ts, readings=readings,
                                           origin=f"synthetic:{spec.name}"))
            seg_elapsed += spec.interval_s
            continue

        readings["cpu.util_pct"] = Reading(round(cpu, 2))
        readings["cpu.util_max_core_pct"] = Reading(
            round(_clamp(cpu * 1.35 + 8.0 * (build > 5.0) + rng.gauss(0, 3), 0.0, 100.0), 2)
        )
        readings["cpu.iowait_pct"] = Reading(round(_clamp(disk * 0.08 + rng.gauss(0, 0.2), 0.0, 100.0), 3))
        readings["cpu.load1_per_core"] = Reading(
            round(_clamp(cpu / 100.0 * 1.1 + rng.gauss(0, 0.05), 0.0, 64.0), 4)
        )
        readings["cpu.freq_mhz"] = Reading(round(_clamp(
            1800.0 + 18.0 * cpu - 3.0 * max(0.0, temp_c - 85.0), 0.0, 12000.0), 1))
        readings["mem.used_pct"] = Reading(round(mem, 2))
        readings["mem.available_gb"] = Reading(
            round(_clamp(16.0 * (1.0 - mem / 100.0), 0.0, 4096.0), 3)
        )
        readings["battery.percent"] = Reading(round(batt_pct, 4))
        readings["battery.plugged"] = Reading(1.0 if plugged else 0.0)
        readings["battery.charging"] = Reading(1.0 if charging else 0.0)
        readings["battery.power_w"] = Reading(round(power_w if not plugged else 0.0, 2))
        readings["gpu.util_pct"] = Reading(round(gpu, 2))
        readings["gpu.power_w"] = Reading(
            round(_clamp(8.0 + 0.62 * gpu + rng.gauss(0, 0.8), 0.0, 800.0), 2)
        )
        readings["thermal.cpu_c"] = Reading(round(_clamp(temp_c, -20.0, 130.0), 2))
        readings["disk.busy_pct"] = Reading(round(_clamp(disk, 0.0, 100.0), 3))
        readings["net.recv_mbps"] = Reading(round(net, 4))
        readings["proc.concentration"] = Reading(
            round(_clamp(0.3 + 0.006 * build + rng.gauss(0, 0.03), 0.0, 1.0), 4)
        )
        readings["proc.cpu_build_pct"] = Reading(round(build, 2))
        # Clamp at the source. Emitting an out-of-range value and letting the
        # normaliser clip it would hide a generator bug behind a legitimate
        # safety net, and it produced a stream of spurious "clamped" warnings.
        readings["proc.top1_cpu_pct"] = Reading(
            round(_clamp(max(build, cpu * 0.45) + rng.gauss(0, 2), 0.0, 6400.0), 2)
        )
        samples.append(
            TelemetrySample(ts=ts, readings=readings, origin=f"synthetic:{spec.name}")
        )
        seg_elapsed += spec.interval_s
    return samples, synthetic_registry()


def _pct_delta(watts: float, spec: ScenarioSpec, sign: int) -> float:
    """Battery percentage change over one tick at ``watts``."""
    wh = watts * (spec.interval_s / 3600.0)
    return sign * 100.0 * wh / max(spec.battery_capacity_wh, 1e-6)


def _current_levels(
    prev: dict[str, float], target: dict[str, float], elapsed: float, ramp_s: float
) -> dict[str, float]:
    if ramp_s <= 0:
        return dict(target)
    f = min(1.0, elapsed / ramp_s)
    # Smoothstep rather than linear: a workload ramp has no corner in it, and a
    # corner would show up as a single enormous slope feature.
    f = f * f * (3.0 - 2.0 * f)
    return {k: prev.get(k, target[k]) + f * (target[k] - prev.get(k, target[k])) for k in target}


def _clamp(x: float, lo: float, hi: float) -> float:
    return lo if x < lo else hi if x > hi else x


# ---------------------------------------------------------------------------
# The scenarios the test suite asserts on.
# ---------------------------------------------------------------------------

def idle_to_build(minutes: float = 90.0, seed: int = 7) -> ScenarioSpec:
    """Scenario 1: idle -> sustained compile -> idle."""
    third = minutes * 60.0 / 3.0
    return ScenarioSpec(
        name="idle_to_build", seed=seed,
        description="Idle machine, a sustained parallel build, then idle again.",
        segments=[
            Segment("idle", third, {"cpu.util_pct": 4.0, "proc.cpu_build_pct": 0.0},
                    {"cpu.util_pct": 1.5}, ramp_s=10.0),
            Segment("build", third,
                    {"cpu.util_pct": 82.0, "proc.cpu_build_pct": 620.0,
                     "mem.used_pct": 71.0, "disk.busy_pct": 35.0},
                    {"cpu.util_pct": 6.0, "proc.cpu_build_pct": 60.0}, ramp_s=45.0),
            Segment("idle_after", third,
                    {"cpu.util_pct": 6.0, "proc.cpu_build_pct": 0.0, "mem.used_pct": 52.0,
                     "disk.busy_pct": 1.0},
                    {"cpu.util_pct": 2.0}, ramp_s=60.0),
        ],
    )


def discharge_then_charge(minutes: float = 120.0, seed: int = 11) -> ScenarioSpec:
    """Scenario 2: unplugged discharge under load, then the charger goes in."""
    half = minutes * 60.0 / 2.0
    return ScenarioSpec(
        name="discharge_then_charge", seed=seed, battery_start_pct=78.0,
        description="Discharge under moderate load, then charging.",
        segments=[
            Segment("unplugged", half, {"cpu.util_pct": 38.0, "gpu.util_pct": 12.0},
                    {"cpu.util_pct": 5.0}, ramp_s=20.0, plugged=False),
            Segment("charging", half, {"cpu.util_pct": 30.0, "gpu.util_pct": 8.0},
                    {"cpu.util_pct": 5.0}, ramp_s=20.0, plugged=True),
        ],
    )


def spike_burst(minutes: float = 60.0, seed: int = 13) -> ScenarioSpec:
    """Scenario 3: steady browsing with short violent CPU spikes."""
    segs: list[Segment] = [
        Segment("browse", 600.0, {"cpu.util_pct": 22.0, "net.recv_mbps": 1.2},
                {"cpu.util_pct": 4.0}, ramp_s=20.0)
    ]
    remaining = minutes * 60.0 - 600.0
    while remaining > 0:
        segs.append(
            Segment("spike", 60.0, {"cpu.util_pct": 95.0, "proc.cpu_build_pct": 300.0},
                    {"cpu.util_pct": 4.0}, ramp_s=5.0)
        )
        segs.append(
            Segment("calm", 240.0, {"cpu.util_pct": 20.0, "proc.cpu_build_pct": 0.0},
                    {"cpu.util_pct": 4.0}, ramp_s=15.0)
        )
        remaining -= 300.0
    return ScenarioSpec(
        name="spike_burst", seed=seed, segments=segs,
        description="Interactive baseline punctuated by one-minute full-load spikes.",
    )


def permanent_regime_change(minutes: float = 180.0, seed: int = 17) -> ScenarioSpec:
    """Scenario 4: behaviour changes permanently halfway through.

    The relationship between the drivers and CPU changes, not just the level:
    before the change CPU is browsing-driven and calm; after, the machine is a
    GPU-heavy workstation with a different mean, variance and coupling. A model
    fitted only on the first half is permanently wrong on the second unless it
    adapts, which is exactly what the drift-triggered arm is supposed to fix.
    """
    half = minutes * 60.0 / 2.0
    return ScenarioSpec(
        name="permanent_regime_change", seed=seed,
        description="Light interactive use, then a permanent switch to GPU-heavy work.",
        segments=[
            Segment("before", half,
                    {"cpu.util_pct": 18.0, "gpu.util_pct": 3.0, "mem.used_pct": 44.0,
                     "net.recv_mbps": 0.8},
                    {"cpu.util_pct": 3.0, "gpu.util_pct": 1.0}, ramp_s=20.0),
            Segment("after", half,
                    {"cpu.util_pct": 58.0, "gpu.util_pct": 88.0, "mem.used_pct": 76.0,
                     "net.recv_mbps": 0.2, "disk.busy_pct": 22.0},
                    {"cpu.util_pct": 9.0, "gpu.util_pct": 5.0}, ramp_s=30.0),
        ],
    )


def gappy_idle(minutes: float = 45.0, seed: int = 19) -> ScenarioSpec:
    """Failure-handling scenario: sensor dropouts and a suspend-sized gap."""
    return ScenarioSpec(
        name="gappy_idle", seed=seed,
        description="Idle machine with 20% sample dropout, for gap handling.",
        segments=[
            Segment("clean", minutes * 60.0 / 3, {"cpu.util_pct": 8.0}, {}, ramp_s=10.0),
            Segment("dropouts", minutes * 60.0 / 3, {"cpu.util_pct": 10.0}, {},
                    ramp_s=10.0, dropout=0.2),
            Segment("clean_after", minutes * 60.0 / 3, {"cpu.util_pct": 9.0}, {}, ramp_s=10.0),
        ],
    )


SCENARIOS = {
    "idle_to_build": idle_to_build,
    "discharge_then_charge": discharge_then_charge,
    "spike_burst": spike_burst,
    "permanent_regime_change": permanent_regime_change,
    "gappy_idle": gappy_idle,
}


def build_scenario(name: str, minutes: float | None = None, seed: int | None = None) -> ScenarioSpec:
    if name not in SCENARIOS:
        raise KeyError(f"unknown scenario {name!r}; have {sorted(SCENARIOS)}")
    fn = SCENARIOS[name]
    kwargs: dict[str, float] = {}
    if minutes is not None:
        kwargs["minutes"] = minutes
    if seed is not None:
        kwargs["seed"] = seed
    return fn(**kwargs)  # type: ignore[arg-type]
